use_frameworks!

target 'Algebraic_Example' do
  pod 'Algebraic', :path => '../'

  target 'Algebraic_Tests' do
    inherit! :search_paths

    
  end
end

install! 'cocoapods',
    :share_schemes_for_development_pods => true
